services:    
  roomba-bridge:
    image: python3-serial
    container_name: roomba-bridge
    restart: unless-stopped
    command: python3 -u bridge.py
    volumes:
      - /home/henry/dev/roomba/bridge/bridge.py:/bridge.py:ro
      - /home/henry/dev/roomba/bridge/settings.py:/settings.py:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

  roomba-livepath:
    image: python3-imaging
    container_name: roomba-livepath
    restart: unless-stopped
    command: python3 -u livepath.py
    volumes:
      - /home/henry/dev/roomba/visuals/livepath.py:/livepath.py:ro
      - /home/henry/dev/roomba/visuals/settings.py:/settings.py:ro
